### ISSUE TITLE
The "-t" option should be dropped like the original emojify. 

### ISSUE THREAD

**Issue by chuanconggao** [lord63/pyemojify#1]

**Comment by lord63** [comment]
Hmmmm, can't get your point now from the title. Could you explain more?

**Comment by chuanconggao** [comment]
What I mean is it would be more clear to write:
`pyemojify "Life is short :smile: , use :sparkles: Python :sparkles:"`
instead of 
`pyemojify -t "Life is short :smile: , use :sparkles: Python :sparkles:"`

This is also the way in the original emojify project.

**Comment by lord63** [comment]
pyemojify use `click` as the CLI, if we use:

```
$ pyemojify "Life is short :smile: , use :sparkles: Python :sparkles:"
```

`click` will treat the text as an argument, so we can't use it when we want to use it via pipeline like this way(because you have to give the input text):

```
$ echo "Life is short :smile: , use :sparkles: Python :sparkles:" | pyemojify
```

The current implement treats the input text as an option and when you don't give the text input, pyemojify will try to get the input text from the standard streams.

As far as I know, use an option will get the task done much easier. If you have other good implementations, let me know :)

**Comment by chuanconggao** [comment]
How about use [docopt](https://github.com/docopt/docopt)? It is easy to write one with the same function in less than 10 lines. 

I have created a pull request #2.

**Comment by lord63** [comment]
The reason why I choose `click` is that it has already handled other things for you, you can just write your program. In my opinion, `docopt` just help you build the interface, you still have to deal with other different situations(By the way, I create a small staff called [wonderful_bing](https://github.com/lord63/wonderful_bing) with `docopt`, used to download bing's picture and set as wallpaper.). For some small and simple command line apps, it may make no difference.
What's more, I'm ok with the `-t` parameter. So, in my personal taste, I still prefer the current implementation. 
Thanks anyway for your suggestions! :sparkles: :cake: :sparkles:
